version: "3.8"

services: 
  db: 
    image: postgres
    restart: always
    ports: 
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: bngocblog
      POSTGRES_PASSWORD: bngocadmin
      POSTGRES_DB: bngoc-blog

  adminer:
    image: adminer
    restart: always
    ports: 
      - 8084:8080
    environment: 
      ADMINER_DEFAULT_SERVER: postgres
      POSTGRES_PASSWORD: bngocadmin